---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsAfterEmpty: 60 # scale down nodes after 60 seconds without workloads
  ttlSecondsUntilExpired: 604800 # expire nodes after 7 days (in seconds)
  limits:
    resources:
      cpu: 100 # limit to 100 CPU cores
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [t3, c5, r5, t2]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [nano, micro, small, medium, large, xlarge]
  providerRef:
    name: my-provider
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: my-provider
spec:
  subnetSelector:
    kubernetes.io/cluster/eks-test-cluster: "shared"
    kubernetes.io/role/internal-elb: "1"
  securityGroupSelector:
    kubernetes.io/cluster/eks-test-cluster: "owned"
